import { Food } from "./food";
import { Tag } from "./tag";

export const Sample_Foods:Food[]=[
    {
        id:"1",
        name:"Pizza",
        price:300,
        cookTime:'40-50',
        favorite:false,
        origins:['itely'],
        stars:4.0,
        imageUrl:'assets/food-1.jpg',
        tags:['Pizza']
    },
    {
        id:"2",
        name:"Manchurians",
        price:199,
        cookTime:'40-50',
        favorite:false,
        origins:['Asia'],
        stars:4.0,
        imageUrl:'assets/food-2.jpg',
        tags:['fastFood']
    },
    {
        id:"3",
        name:"Burgur",
        price:150,
        cookTime:'40-50',
        favorite:false,
        origins:['USA'],
        stars:3.5,
        imageUrl:'assets/food-3.jpg',
        tags:['fastFood','Hamburger']
    },
    {
        id:"4",
        name:"French-Fries",
        price:289,
        cookTime:'40-50',
        favorite:false,
        origins:['Sweden'],
        stars:4.1,
        imageUrl:'assets/food-4.jpg',
        tags:['fastFood','Fry']
    },
    {
        id:"5",
        name:"Manchow Suap",
        price:99,
        cookTime:'40-50',
        favorite:false,
        origins:['China'],
        stars:3.0,
        imageUrl:'assets/food-5.jpg',
        tags:['fastFood','Lunch','Soup']
    },
    {
        id:"6",
        name:"Tooping Pizza",
        price:500,
        cookTime:'40-50',
        favorite:false,
        origins:['Itely'],
        stars:5.0,
        imageUrl:'assets/food-6.jpg',
        tags:['fastFood','Pizza']
    },
    {
        id:'7',
        name:"Biriyani",
        price:350,
        cookTime:"40-50",
        favorite:false,
        origins:["India"],
        stars:3.0,
        imageUrl:'assets/food-7.jpeg',
        tags:['Meals','Lunch','Dinner']
      }
      ,{
        id:'8',
        name:"Momos",
        price:150,
        cookTime:"40-50",
        favorite:false,
        origins:["India","Nepal"],
        stars:4.5,
        imageUrl:'assets/food-8.jpeg',
        tags:['Meals','Lunch','Fry']
      }
      ,{
        id:'9',
        name:"Nuddels",
        price:200,
        cookTime:"40-50",
        favorite:false,
        origins:["America"],
        stars:4.0,
        imageUrl:'assets/food-9.jpeg',
        tags:['Fast-food','Snack',]
      }
      ,{
        id:'10',
        name:"Chicken nuggets ",
        price:330,
        cookTime:"40-50",
        favorite:false,
        origins:["chinese"],
        stars:5.0,
        imageUrl:'assets/food-10.jpeg',
        tags:['Fast-food','Snack']
      }
      ,{
        id:'11',
        name:"Butter-Chicken",
        price:350,
        cookTime:"40-50",
        favorite:false,
        origins:["India"],
        stars:4.5,
        imageUrl:'assets/food-11.jpeg',
        tags:['Snack','Lunch']
      }
      ,{
        id:'12',
        name:" Panner Paratha",
        price:250,
        cookTime:"40-50",
        favorite:false,
        origins:["India"],
        stars:4.0,
        imageUrl:'assets/food-12.jpeg',
        tags:['Lunch']
      },
      {
        id:'13',
        name:"Chicken thali",
        price:360,
        cookTime:"40-50",
        favorite:false,
        origins:["India"],
        stars:4.0,
        imageUrl:'assets/food-13.jpeg',
        tags:['Lunch']
      },
      {
        id:'14',
        name:"Handi",
        price:560,
        cookTime:"40-50",
        favorite:false,
        origins:["India"],
        stars:4.0,
        imageUrl:'assets/food-14.jpeg',
        tags:['Lunch']
      },
      {
        id:'15',
        name:"Fried Fish",
        price:299,
        cookTime:"40-50",
        favorite:false,
        origins:["India"],
        stars:4.0,
        imageUrl:'assets/food-15.jpeg',
        tags:['Lunch']
      }
      ,{
        id:'16',
        name:"Anda Biryani",
        price:160,
        cookTime:"40-50",
        favorite:false,
        origins:["India"],
        stars:4.1,
        imageUrl:'assets/food-16.jpeg',
        tags:['Lunch']
      },
      {
        id:'17',
        name:"Chicken Malvani",
        price:399,
        cookTime:"40-50",
        favorite:false,
        origins:["India"],
        stars:5.1,
        imageUrl:'assets/food-17.jpeg',
        tags:['Lunch']
      }
      ,{
        id:'18',
        name:"Chicken fried",
        price:250,
        cookTime:"40-50",
        favorite:false,
        origins:["India"],
        stars:4.3,
        imageUrl:'assets/food-18.jpeg',
        tags:['Lunch']
      }
     ,{
        id:'19',
        name:"Chicken Showrma",
        price:120,
        cookTime:"15-20",
        favorite:false,
        origins:["India"],
        stars:3.0,
        imageUrl:'assets/food-19.jpeg',
        tags:['Lunch']
      },
      {
        id:'20',
        name:"Gulab-Jam",
        price:99,
        cookTime:"10",
        favorite:false,
        origins:["India"],
        stars:4.5,
        imageUrl:'assets/food-20.jpeg',
        tags:['Sweet']
      }
]
export const sample_tags:Tag[]=[
  { name:'All',count:12},
  {name:'Fast-food',count:2},
  {name:'Pizza',count:2},
  {name:'Lunch',count:5},
  {name:'SlowFood',count:5},
  {name:'Hamburger',count:1},
  {name:'Fry',count:2},
  {name:'Soup',count:1}
]
